site_name: Abyss Render Hardware Interface
site_description: aby-rhi documentation
site_author: xexaaron
site_dir: bin/docs
copyright: Copyright &copy; 2026 xexaaron
repo_url: https://github.com/xexaaron/aby-rhi

nav:
  - Home: index.md
  - Introduction:
    - Getting Started: introduction/getting-started.md
    - Quick Start: introduction/quick-start.md
  - Api Overview:
    - Interfaces: api/interfaces.md
  - Api: 
    - Class Table Of Contents: rhi\annotated.md
    - Files: rhi\files.md
    - Namespaces: rhi\namespaces.md
    - Classes: rhi\classes.md
    - Functions: rhi\namespace_member_functions.md
    - Globals/Constants: rhi\namespace_member_variables.md
    - Typdefs: rhi\namespace_member_typedefs.md
    - Enums: rhi\namespace_member_enums.md
    - Macros: rhi\macros.md

theme:
  name: material
  language: en

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight
    - content.grid

  highlightjs: true
  hljs_languages:
    - bash
    - cmake
    - cpp
    - glsl
    - yaml
    - json

extra_css:
  - stylesheets/extra.css

hooks:
  - docs/hooks/repo_url.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdoxy:
      projects:
        rhi:
          src-dirs: include/aby-rhi
          full-doc: True